=== akritiko/creative-commons/MSc Coursework/Essay & Code - PROTEGE - Advanced Data Mining/exercise02/Web2User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.newsfilter.gr/Web2User" xmlns:tns="http://www.newsfilter.gr/Web2User" elementFormDefault="qualified">

    <complexType name="web2Persona">
    	<sequence>
    		<element name="nickname" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="fullname" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="memberOf" type="tns:memberOf" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="follows" type="tns:friends"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="followedBy" type="tns:followers"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>


    <complexType name="memberOf">
    	<sequence>
    		<element name="service" type="tns:web2Service" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="web2Service">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="uniqueURL" type="string"></attribute>
    </complexType>

    <element name="webPersona" type="tns:web2Persona"></element>

    <complexType name="friends">
    	<sequence>
    		<element name="atService" type="tns:atService" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="atService">
    	<sequence>
    		<element name="contactID" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="followers">
    	<sequence>
    		<element name="atService" type="tns:atService" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== akritiko/creative-commons/MSc Coursework/Essay & Code - PROTEGE - Advanced Data Mining/exercise02/Web2User.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:webPersona id="akritiko@gmail.com" xmlns:tns="http://www.newsfilter.gr/Web2User" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.newsfilter.gr/Web2User Web2User.xsd ">
  <tns:nickname>akritiko</tns:nickname>
  <tns:fullname>Apostolos Kritikos</tns:fullname>
  <tns:memberOf>
    <tns:service name="twitter" uniqueURL="http://twitter.com/akritiko"/>
    <tns:service name="youtube" uniqueURL="http://www.youtube.com/user/akritiko"/>
  </tns:memberOf>
  <tns:follows>
    <tns:atService name="twitter">
      <tns:contactID>asynadak</tns:contactID>
      <tns:contactID>chzigkol</tns:contactID>
    </tns:atService>
    <tns:atService name="youtube">
      <tns:contactID>asynadak</tns:contactID>
    </tns:atService>
  </tns:follows>
  <tns:followedBy>
    <tns:atService name="twitter">
      <tns:contactID>abraxas</tns:contactID>
      <tns:contactID>chzigkol</tns:contactID>
    </tns:atService>
    <tns:atService name="youtube">
      <tns:contactID>asynadak</tns:contactID>
    </tns:atService>
  </tns:followedBy>
</tns:webPersona>
